name: mind_fence
description: A comprehensive social media blocking app to help users increase productivity and reduce digital distractions.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^13.2.0
  
  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # HTTP & Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  
  # Utilities
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  permission_handler: ^11.1.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Firebase (for future implementation) - temporarily disabled
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  # firebase_analytics: ^10.7.4
  
  # Platform-specific blocking
  # usage_stats: ^1.3.0  # Android usage stats - temporarily disabled
  # app_usage: ^3.0.0    # Cross-platform app usage - temporarily disabled
  
  # VPN/Proxy for website blocking
  # flutter_vpn: ^0.13.0  # temporarily disabled
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  # Fonts
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700